# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1efa8e379fafe00e5a4c611e40aa67b2ca6657fc176ab5e06659fcc3914ac9e10c5085f7b9c4cf5844caca3bb93db305eb54c2f9905272bb508d44b79b326830

test:
  secret_key_base: a77bbce3febad4c086c05035ae8d398f3736965790a5f5b31219a96fda21b47676cd9a4c5e872b621a0761e9ac4f17be17a75e7c74bf026cb5cfbed4bc763cff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
